### ISSUE TITLE
Nova layout efinanceira

### ISSUE THREAD

**Issue by rodrigocostarcs** [nfephp-org/sped-efinanceira#122]
Oi boa tarde, recentemente ao tentar enviar o efinanceira no evento de abertura usando a última TAG válida do projeto, recebi um erro avisando que o layout mudou, ao validar no site da receita eu vi que realmente foi publicado um manual com novas mudanças de layout, segue o link: 
http://sped.rfb.gov.br/arquivo/show/1767

Gostaria de saber se vai alterações referente ao novo layout?

![Captura de Tela 2023-11-03 às 15 22 21](https://github.com/nfephp-org/sped-efinanceira/assets/29698011/5f19c7d8-e175-4760-aff5-345a2c797359)

**Comment by robmachado** [comment]
Se o amigo, olhar o pacote vai ver que tem as versões 1.2.0, 1.2.1, 1.2.2, 1.2.3 e 1.2.4
Não custa nadinha navegar um pouco e olhar ANTES de perguntar
